name: LitTournaments
version: '${project.version}'
main: me.waterarchery.littournaments.LitTournaments
api-version: '1.13'
authors: [ WaterArchery ]
description: Create fun tournaments for players
softdepend:
  - NuVotifier
  - Votifier
  - CrazyCrates
  - ExcellentCrates
  - Essentials
  - EssentialsX
  - Duels
  - MythicMobs
depend:
  - LitLibs